In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
array2 = numpy.array([[2, 3, 5, 7],[6, 11, 13, 17], [19, 23, 29, 31]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 2,  3,  5,  7],
       [ 6, 11, 13, 17],
       [19, 23, 29, 31]])

In [9]:
array2.shape

(3, 4)

In [10]:
array1.size

11

In [11]:
array2.size

12

In [12]:
array3 = numpy.full(6,7)

In [13]:
print(array3)

[7 7 7 7 7 7]


In [14]:
array3 = numpy.full(6, 0)
array4 = numpy.zeros(6, dtype=int)

print(array3)
print(array4)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


``numpy``의 ``random``모듈의 ``random``함수를 사용하면 랜덤한 값을 생성할 수 있다.

In [15]:
array3 = numpy.random.random(6)
array4 = numpy.random.random(6)

print(array3)
print()
print(array4)

[0.51935397 0.8236115  0.02123849 0.00369922 0.9862378  0.48576737]

[0.71936403 0.0438162  0.57154993 0.74196    0.5524414  0.71692044]


## 연속된 값들이 담긴 numpy array 생성

``numpy``모듈의 ``arange``함수를 사용하면 연속된 값들이 담겨 있는 **numpy array**를 생성할 수 있다

아래에 각각 파라미터가 하나 혹은 둘, 셋인 경우에 따른 결과물

In [16]:
array1 = numpy.arange(6)

print(array1)

[0 1 2 3 4 5]


In [17]:
array1 = numpy.arange(2, 7)

print(array1)

[2 3 4 5 6]


In [18]:
array1 = numpy.arange(2, 17, 3)

print(array1)

[ 2  5  8 11 14]


## 모듈 별명 지어주기

In [19]:
import numpy as np

```python
import numpy as np
```
에서 as **np**는  numpy의 별명과 같이 사용된다.

In [20]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6)
array3 = numpy.full(6, 6)
array4 = numpy.random.random(6)

위 값이나

In [21]:
array1 = np.full(6, 0)
array2 = np.zeros(6)
array3 = np.full(6, 6)
array4 = np.random.random(6)

이 값은 같은 값을 갖게 된다(물론 ``random``함수 안에 있는 숫자 빼고)

### 문제. 1부터 100까지의 숫자가 담긴 array 만들기

In [22]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### 100보다 작은 3의 배수들이 담긴  array 만들기

In [23]:
arr = np.arange(3, 100, 3)

arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## 인덱싱과 슬라이싱

In [24]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [25]:
array1[0]

2

In [26]:
array1[2]

5

In [27]:
array1[-1]

31

In [28]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

위 처럼 `array`안에 리스트를 넣어주면 각 인덱스에 해당하는 숫자를 꺼내준다

In [29]:
array2 = np.array([2, 1, 3])

In [30]:
array1[array2]

array([5, 3, 7])

위와 같이 `array`안에 `array`를 가지고 인덱싱을 할 수도 있다.

In [31]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [32]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [33]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

array1[x: y: z]를 할 경우 z는 `array`에서 끄집어낼 간격을 말한다.

## numpy의 기본연산

In [34]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [35]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [39]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [41]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

In [42]:
yen_array = np.array(revenue_in_yen)
dollar_array = np.array(revenue_in_dollar)
won_array = (yen_array * 10.08) + (dollar_array * 1138)

In [43]:
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

## numpy의 불린 연산

In [44]:
import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [45]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [46]:
array1 % 2 == 0 

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [47]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [48]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [49]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [50]:
filter = np.where(array1 > 4)

In [51]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

### 문제. 흥부부대찌개 목표 일 매출

흥부부대찌개 집의 일매출이 20만원 이하였던 때만을 골라 array에 담아 산출하기

In [52]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
yen_array = np.array(revenue_in_yen) # 리스트를 array로 변환
filter = np.where(yen_array <= 200000) # 20만원 이하 매출 인덱스만 찾아 filter에 담기
bad_days_revenue = yen_array[filter]

# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

# numpy 기본 통계

``numpy``라이브러리는 기본적인 통계 기능도 제공한다

In [53]:
import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최대값
print(array1.min()) # 최소값

31
5


``max``와 ``min``메소드를 사용하면 각각 최대값과 최소값을 구할 수 있다.

In [54]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean()) # 평균값

15.25


``mean``메소드를 사용하면 numpy array의 평균값을 구할 수 있음

In [55]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값

12.0
13.5


``meadian`` 메소드를 사용하면 중앙값을 구할 수 있다. 단, ``meadian``은 numpy array 의 메소드가 아니라 numpy의 메소드이기 때문에 용법에 차이가 있으니 명심하도록!

In [56]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 분산
print(array1.var()) # 표준편차

8.496322733983215
72.1875
